-- Supabase / PostgreSQL Schema for CloudPOS

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'staff',
    pin TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

-- 3. Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sku TEXT UNIQUE NOT NULL,
    price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    cost NUMERIC(15, 2) NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tax NUMERIC(15, 2) NOT NULL DEFAULT 0,
    discount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    payment_method TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

-- 5. Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC(15, 2) NOT NULL
);

-- 6. Receipt Settings Table
CREATE TABLE IF NOT EXISTS receipt_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    business_name TEXT,
    branch_name TEXT,
    address TEXT,
    phone TEXT,
    tax_id TEXT,
    logo_url TEXT,
    footer_message TEXT,
    return_policy TEXT,
    show_tax INTEGER DEFAULT 1,
    show_cashier INTEGER DEFAULT 1,
    show_sku INTEGER DEFAULT 1,
    font_size TEXT DEFAULT 'medium'
);

-- 7. Receipts Table
CREATE TABLE IF NOT EXISTS receipts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    type TEXT, -- customer, merchant, kitchen, refund, gift_card
    status TEXT, -- printed, digital_only
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Receipt Taxes Table
CREATE TABLE IF NOT EXISTS receipt_taxes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id UUID REFERENCES receipts(id) ON DELETE CASCADE,
    tax_name TEXT NOT NULL,
    rate NUMERIC(5, 2) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL
);

-- 9. Print Logs Table
CREATE TABLE IF NOT EXISTS print_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id UUID REFERENCES receipts(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    print_type TEXT,
    status TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SEED DATA

-- Initial User (admin/admin)
INSERT INTO users (username, password, role, pin) 
VALUES ('admin', 'admin', 'owner', '1234')
ON CONFLICT (username) DO NOTHING;

-- Initial Categories
INSERT INTO categories (name) VALUES ('Beverages'), ('Food'), ('Merchandise')
ON CONFLICT (name) DO NOTHING;

-- Initial Receipt Settings
INSERT INTO receipt_settings (
    id, business_name, branch_name, address, phone, tax_id, footer_message, return_policy
) VALUES (
    1, 
    'CloudPOS Coffee Co.', 
    'Downtown Branch', 
    '123 Innovation Way, Tech City', 
    '+1 (555) 000-1234', 
    'VAT-987654321', 
    'Thank you for your business!', 
    'Returns accepted within 30 days with receipt.'
) ON CONFLICT (id) DO NOTHING;

-- Initial Products
DO $$
DECLARE
    bev_id BIGINT;
    food_id BIGINT;
    merch_id BIGINT;
BEGIN
    SELECT id INTO bev_id FROM categories WHERE name = 'Beverages';
    SELECT id INTO food_id FROM categories WHERE name = 'Food';
    SELECT id INTO merch_id FROM categories WHERE name = 'Merchandise';

    INSERT INTO products (name, sku, price, cost, stock, category_id) VALUES 
    ('Espresso', 'COF-001', 3000, 500, 100, bev_id),
    ('Latte', 'COF-002', 4500, 800, 100, bev_id),
    ('Cappuccino', 'COF-003', 4250, 750, 100, bev_id),
    ('Croissant', 'FOD-001', 3750, 1200, 50, food_id),
    ('Muffin', 'FOD-002', 3250, 900, 40, food_id),
    ('CloudPOS Tee', 'MER-001', 25000, 10000, 20, merch_id)
    ON CONFLICT (sku) DO NOTHING;
END $$;

-- RPC for Stock Management
CREATE OR REPLACE FUNCTION decrement_stock(row_id BIGINT, amount INTEGER)
RETURNS void AS $$
BEGIN
  UPDATE products
  SET stock = stock - amount
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;
